### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mudlord** [mudlord/mupack#1]
- [x] Rewrite to use PE_Bliss (fixing many issues in the process)
- [x] More compression methods (LZ4, BriefLZ)
- [x] Optimize LZMA depacker

**Comment by mudlord** [comment]
Note: PE_Bliss rewrite is currently in mupakk (note the spelling), but could be backported to mupack (public version)

**Comment by mudlord** [comment]
PE_Bliss rewrite now added to public git.

**Comment by mudlord** [comment]
Added buildbot.

**Comment by mudlord** [comment]
https://modexp.wordpress.com/2019/12/08/shellcode-compression/#d3d
